version: '3.9'

networks:
  fuel-meter-net:
    name: fuel-meter-net
services:
  queue:
    container_name: fuel-meter-redis
    image: redis:7.2.3
    networks:
      - fuel-meter-net
    ports:
      - "60000:6379"
  #api:
  #  container_name: fuel-meter-api
  #  build:
  #    context: .
  #    network: host
  #  depends_on:
  #    - queue
  #  networks:
  #    - fuel-meter-net
  #  ports:
  #    - "3000:3000"
  #  environment:
  #    - HTTP_PORT=3000
  #    - APP_NAME=fuel-meter-api
  #    - REDIS_URL=redis://queue
  #    - JWT_KEY=poggone
  #    - RUST_BACKTRACE=1
  #    - RUST_LOG=trace
  #  volumes:
  #    - ./src:/code/src
  #  entrypoint: ["cargo", "watch", "-x", "run -- --conf-path=2 --templates-path=4"]