name: build docker image

on:
    push:
        branches: [main]

env:
  REGISTRY: docker.io
  REGISTRY_IMAGE: emilianomaccaferri/pieno-fuel-meter

jobs:
    notify-webhook:
      runs-on: ubuntu-latest
      steps:
        - name: notify webhook because it's better
          uses: actions/checkout@v3
        - run: curl -X POST https://hooks.macca.cloud/pieno/build/fuel-meter

        