name: build docker image

on:
    push:
        branches: [main]

jobs:
    registry_push:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v4
            
            - name: qemu for multiplatform
              uses: docker/setup-qemu-action@v3

            - name: docker buildix setup
              uses: docker/setup-buildx-action@v3
            
            - name: docker login
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_TOKEN }}
            
            - name: metadata
              uses: docker/metadata-action@v3
              with:
                images: emilianomaccaferri/pieno-fuel-meter
            
            - name: build&push
              uses: docker/build-push-action@v5
              with:
                context: .
                file: ./Dockerfile.actions
                platforms: linux/amd64,linux/arm64
                push: true
                tags: ${{ github.sha }}


        